security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
                # property: username  # comment this to use loadUserByUsername() method on UserRepository will be called.

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # pattern: ^/
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: login
                check_path: login2
                target_path_parameter: address_list
                failure_path_parameter: failed_login
                require_previous_session: false
            logout:
                path: /logout
                target: /logout/success
                invalidate_session: true

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login2, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/createuser, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/address/list, roles: IS_AUTHENTICATED_ANONYMOUSLY }
