security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
                # property: username  # comment this to use loadUserByUsername() method on UserRepository will be called.
        api_key_user_provider:
                id: authentication.api_key_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_calls:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: authentication.apikey_authenticator
            provider: api_key_user_provider

        main:
            pattern: ^/
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: login
                check_path: login
                target_path_parameter: _target_path
                failure_path_parameter: _failed_login
                require_previous_session: false
            logout:
                path: /logout
                target: /logout/success
                invalidate_session: true

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
            # most auth requirements are sett as annotation but some are better to keep here
            # require ROLE_ADMIN for /admin*
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/failed_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/createuser, roles: IS_AUTHENTICATED_ANONYMOUSLY }

